### PR TITLE
fix/251/server/deleting-user-in-namespaces

### LINKED ISSUE #251: user still available at lower hierarchy even though he has been deleted at higher hierarchy
ex : when we delete a user at application level , at space level we are still able to add the user to a role .

### PR DESCRIPTION
**Pull request by surajmn1**
closes #251

### CODE REVIEW

File: server/action/organisation/user/delete.go [hunk 1]
```diff
@@ -90,15 +93,26 @@ func delete(w http.ResponseWriter, r *http.Request) {
...
-			Relation:  result.Role, // relation is an empty string to avoid addition of the relation query parameter
-		},
-		SubjectID: fmt.Sprintf("%d", uID),
+	err = user.DeleteUserFromOrganisationRoles(uint(orgID), result.UserID)
+	if err != nil {
+		loggerx.Error(err)
+		errorx.Render(w, errorx.Parser(errorx.InternalServerError()))
+		return
+	}
+	err = user.DeleteUserFromApplications(uint(orgID), result.UserID)
```
Comment (vsumit89) [inline server/action/organisation/user/delete.go:102]: @surajmn1 handle the error on line 102

**Review by vsumit89 — DISMISSED** [review]

**Review by vsumit89 — APPROVED** [review]
