### PR TITLE
Fix/application UI

### LINKED ISSUE #2: Change the User Avatar Image to imgproxy link
Some image sources are using storage URL change that to imgproxy Link.

### LINKED ISSUE #45: Applications UI is confusing, make it consistent to the rest of the entities
Applications entity is not consistent with the rest of the UI in Dega or other applications. Make the following changes:

- [x] Clicking on Edit should take to the application page where `Tokens` should show up as well. Currently, you click on the name of the application to get to the tokens
- [x] Breadcrumb is just showing `applications` regardless of the application it is in. When you click on `Edit`, the breadcrumb should be `Applications/<application-name>`
- [x] Change the label from `New api key` to `New API Token`
- [x] Change the dialog title from `Generate Api key` to `Create New API Token` 
- [x] Delete the `return` button in the API creation dialog. It is redundant. Users can close the dialog by `X` on the top.
- [x] Change the button label from `Submit` to `Create API Token` and move the button to the bottom of the dialog.
- [x] Change the description to multiline input

### PR DESCRIPTION
**Pull request by Bhumi101097**
Application UI changes
Closes #45 

Changed Image link to proxy
Closes #2

### CODE REVIEW

File: web/src/pages/application/components/ApplicationForm.js [hunk 1]
```diff
@@ -92,6 +92,9 @@ const ApplicationForm = ({ onCreate, data = {} }) => {
       >
         <Input />
       </Form.Item>
+      <Form.Item label="Token">
+        <GetApplication />
+      </Form.Item>
```
Comment (shreeharsha-factly) [inline web/src/pages/application/components/ApplicationForm.js]: Once the application is created then only a token can be generated. So please separate the Application form and tokens table.

**Review by shreeharsha-factly — CHANGES_REQUESTED** [review]

**Comment by shreeharsha-factly** [comment]
@Bhumi101097 Can't create a new application.

File: web/src/components/PageHeader/index.js [hunk 2]
```diff
@@ -19,7 +23,28 @@ function PageHeader() {
           breadcrumbName: route.title,
         };
       } else {
-        return null;
+        if (pathSnippets.includes('edit') && !state[entity].loading) {
```
Comment (shreeharsha-factly) [inline web/src/components/PageHeader/index.js:26]: @Bhumi101097 Instead of checking entities loading state check whether we have that entity or not.

**Review by shreeharsha-factly — CHANGES_REQUESTED** [review]

File: web/src/pages/application/EditApplication.js [hunk 3]
```diff
@@ -28,7 +30,20 @@ function EditApplication() {
...
+  return (
+    <Space direction="vertical" style={{ width: '100%' }}>
+      <Collapse>
+        <Panel header="Application Details" key="1">
+          <ApplicationEditForm data={application} onCreate={onUpdate} />
+        </Panel>
+      </Collapse>
+      <Collapse>
+        <Panel header="Tokens" key="2">
+          <GetApplication />
```
Comment (shreeharsha-factly) [inline web/src/pages/application/EditApplication.js]: @Bhumi101097  pass application data as a prop to  `GetApplication` component. And remove getApplication action in  `GetApplication` component.

**Review by shreeharsha-factly — CHANGES_REQUESTED** [review]

File: web/src/pages/application/EditApplication.js [hunk 4]
```diff
@@ -28,7 +31,20 @@ function EditApplication() {
...
+          <ApplicationEditForm data={application} onCreate={onUpdate} />
+        </Panel>
+      </Collapse>
+      <Collapse>
+        <Panel header="Tokens" key="2">
+          <GetApplication setTokenFlag={setTokenFlag} data={application} />
+        </Panel>
+      </Collapse>
+    </Space>
+  );
```
Comment (shreeharsha-factly) [inline web/src/pages/application/EditApplication.js:47]: @Bhumi101097 Can you open these panels by default.

**Review by shreeharsha-factly — APPROVED** [review]
